# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  gcp-gke: circleci/gcp-gke@1.0.3
# Orchestrate or schedule a set of jobs
workflows:
  publish-and-rollout-image:
    jobs:
      - gcp-gke/publish-and-rollout-image:
          filters:
            branches:
              only:
                - master
                - dev
          pre-steps:
            - run:
                name: Set APP_ENV and CLUSTER_NAME
                command: |
                  echo "Setting env vars for branch $CIRCLE_BRANCH"
                  if [ "$CIRCLE_BRANCH" = "dev" ]
                  then
                    echo 'export APP_ENV=dev' >> $BASH_ENV
                    echo 'export CLUSTER_NAME=mytwiga-dev-1' >> $BASH_ENV
                  else
                    echo 'export APP_ENV=prod' >> $BASH_ENV
                    echo 'export CLUSTER_NAME=mytwiga-prod-1' >> $BASH_ENV
                  fi
                  source $BASH_ENV
                  echo "APP_ENV set to $APP_ENV and CLUSTER_NAME to $CLUSTER_NAME"                   
          context: global
          cluster: $CLUSTER_NAME
          deployment: mytwiga-defi
          container: defi
          namespace: web
          image: mytwiga-defi
          registry-url: eu.gcr.io
          tag: $CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
          extra-build-args: '--build-arg APP_ENV'